
package interfaces;

import java.sql.*;
import conexion.*;
import java.awt.Image;
import java.awt.Toolkit;

public class EditarEstatusMapa extends javax.swing.JFrame {

    String ciudad = ControlMapa.ciudad_a_editar;
    
    public EditarEstatusMapa() {
        initComponents();
        setSize(300,150);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Editar " + ciudad);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        txt_Ciudad.setText(ciudad);
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                "select * from gobernadores where Ciudad = '"+ ciudad +"'");
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                txt_Nuevo_Estatus.setText(rs.getString("Estatus"));
            }
            cn.close();

        } catch (SQLException e) {
            System.err.println("Error al tomar estatus: "+e);
        }
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/IconoAsistenteIndependencia.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_Ciudad = new javax.swing.JTextField();
        jButton_ActualizarEstatus = new javax.swing.JButton();
        txt_Nuevo_Estatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo Estatus");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, -1));

        txt_Ciudad.setEnabled(false);
        getContentPane().add(txt_Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 30));

        jButton_ActualizarEstatus.setText("Actualizar");
        jButton_ActualizarEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarEstatusActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ActualizarEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));
        getContentPane().add(txt_Nuevo_Estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ActualizarEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarEstatusActionPerformed

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                "update gobernadores set Estatus = ? where Ciudad = '"+ciudad+"'");

            pst.setInt(1, Integer.parseInt(txt_Nuevo_Estatus.getText()));
            pst.executeUpdate();
            cn.close();

        } catch (SQLException e) {
            System.err.println("Error al actualizar nuevo Estatus desde mapa: "+e);
        }
        
        this.dispose();

    }//GEN-LAST:event_jButton_ActualizarEstatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEstatusMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEstatusMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEstatusMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEstatusMapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEstatusMapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ActualizarEstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_Ciudad;
    private javax.swing.JTextField txt_Nuevo_Estatus;
    // End of variables declaration//GEN-END:variables
}
